version: "3.1"
services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python_3.1.5_container_uw
    ports:
      - 80:80
    volumes:
      - ./:/app
    networks:
      - bottle_arangodb_network

  arangodb:
    image: arangodb:3.11.3
    container_name: arango_3.11.3_container_uw
    restart: always
    ports:
      - 8529:8529
    environment:
      - ARANGO_NO_AUTH=1
    volumes:
      - ./arangodb:/var/lib/arangodb3
    networks:
      - bottle_arangodb_network

networks:
  bottle_arangodb_network:
